---
- name: make filebeat cert directory
  file:
    path: /etc/pki/tls/certs
    state: directory
    mode: 0755
    owner: root
    group: root
  
- name: copy filebeat cert
  copy:
    src: /etc/pki/tls/certs/logstash-forwarder.crt
    dest: /etc/pki/tls/certs/
    mode: 0644
    owner: root
    group: root

- name: import/validate filebeat gpg key
  rpm_key:
    key: http://packages.elastic.co/GPG-KEY-elasticsearch
    state: present
    validate_certs: yes
  when: ( ansible_distribution == "CentOS" or ansible_distribution == "Fedora" ) and ( ansible_distribution != "Archlinux" )

- name: copy filebeat repo file
  copy:
    src: /etc/yum.repos.d/elastic-beats.repo
    dest: /etc/yum.repos.d
    mode: 0644
    owner: root
    group: root
    
- name: install packetbeat 
  dnf:
    name: "{{ item }}"
    state: present
  with_items: [ 'packetbeat' ]
  when: ansible_distribution == "Fedora"

- name: install packetbeat
  pacman:
    name: "{{ item }}"
    state: present
  with_items: [ 'packetbeat' ]
  when: ansible_distribution == "Archlinux"

- name: copy over packetbeat config
  copy:
    src: /etc/packetbeat/packetbeat.yml
    dest: /etc/packetbeat/
    mode: 0644
    owner: root
    group: root

- name: start and enable packetbeat
  systemd:
    name: packetbeat
    enabled: yes
    state: restarted
