---
- hosts: all 
  tasks:
  - name: update yum
    yum:
      name: '*yum*'
      state: latest
    when: ansible_distribution == "Fedora" or ansible_distribution == "CentOS"

  - name: update kernel
    yum:
      name: '*kernel*'
      state: latest
    when: ansible_distribution == "Fedora" or ansible_distribution == "CentOS"
 
  - name: update all - arch
    pacman:
      update_cache: yes
      upgrade: yes
    register: result
    when: ansible_distribution == "Archlinux"

  - debug: var=result

  - name: update all - rh
    yum:
      name: '*'
      state: latest
    register: result
    when: ansible_distribution == "CentOS" or ansible_distribution == "Fedora"
  - debug: var=result

  - name: yum clean up to conserve space 
    command: yum clean all
    when: ansible_distribution == "Fedora" or ansible_distribution == "CentOS"
