---
- hosts: all 
  tasks:
  - name: update /opt/scripts
    copy:
      src: /opt/scripts/
      dest: /opt/scripts/
      follow: yes
      owner: root
      group: wheel
      mode: 0774

  - name: update yum
    yum:
      name: '*yum*'
      state: latest
    when:  ansible_distribution == "CentOS"

  - name: update kernel
    yum:
      name: '*kernel*'
      state: latest
    when:  ansible_distribution == "CentOS"

  - name: update all - rh
    yum:
      name: '*'
      state: latest
    when: ansible_distribution == "CentOS"

  - name: yum clean all - rh yum
    command: "yum clean all"
    when: ansible_distribution == "CentOS"

  - name: update dnf
    dnf:
      name: '*dnf*'
      state: latest
    when: ansible_distribution == "Fedora"

  - name: update kernel
    dnf:
      name: '*kernel*'
      state: latest
    when: ansible_distribution == "Fedora"
 
  - name: update all - fedora
    dnf:
      name: '*'
      state: latest
    when: ansible_distribution == "Fedora"

  - name: dnf clean all -dnf rh
    command: "dnf clean all"
    when: ansible_distribution == "Fedora"

  - name: update all - arch
    pacman:
      update_cache: yes
      upgrade: yes
    when: ansible_distribution == "Archlinux"
